### ISSUE TITLE
Automatize download process

### ISSUE THREAD

**Issue by alex73630** [alex73630/Floatplane-Downloader#2]
Actually the only way to automatize check and download would be to run script in a cron job (for Linux systems)

For my own server, I added this in my crontab:
`0 */4 * * * cd /home/alex73630/floatplane-downloader/ && node index.js`
Where it launches the script once every 4 hours.

But I have an issue with this:

    /home/alex73630/floatplane-downloader/index.js:79
                            for (let i = 1; i < 10; i++) {
                                 ^^^
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Function.Module.runMain (module.js:441:10)
        at startup (node.js:140:18)
        at node.js:1043:3

Certainly due to the way that cron works (specific account, special permissions).

Two way to fix this issue, finding why cron does this (but this will only allows Linux users to automatize) or we can add an auto check every x hours if there is any new videos.

**Comment by alex73630** [comment]
Fixed by commit 35c1d6e32588dae86a4b41dee5cbffbfa3174d75
Close #2
